dictionaries = ["en_us"]
words = [
    "alignable",
    "assocs",
    "colour",
    "downto",
    "groupable",
    "hardline",
    "idents",
    "inout",
    "leftof",
    "lits",
    "nand",
    "nthen",
    "objs",
    "punct",
    "rightof",
    "rol",
    "ror",
    "sev",
    "sll",
    "srl",
    "stmts",
    "succ",
    "unformatted",
    "vunit",
    "vunits",
    "xnor"
]
include_paths = [
    "**/*.rs",
]
use_global = false
min_word_length = 0
