array_width = 80
attr_fn_like_width = 90
# blank_lines_lower_bound = 1 # unstable yet
chain_width = 80
# comment_width = 100 # unstable yet
# condense_wildcard_suffixes = true # unstable yet
# enum_discrim_align_threshold = 20 # unstable yet
fn_call_width = 80
# format_strings = true # unstable yet
# hex_literal_case = "Upper" # unstable yet
# float_literal_trailing_zero = "IfNoPostfix" # unstable yet
# imports_layout = "HorizontalVertical" # unstable yet
# imports_granularity = "Module" # unstable yet
newline_style = "Unix"
# reorder_impl_items = true # unstable yet
# group_imports = "StdExternalCrate" # unstable yet
single_line_if_else_max_width = 80
# struct_field_align_threshold = 20 # unstable yet
max_width = 100
# wrap_comments = true # unstable yet
