-- megafunction wizard: %ALTREMOTE_UPDATE%
-- GENERATION: STANDARD
-- VERSION: WM1.0
-- MODULE: altremote_update 

-- ============================================================
-- File Name: ASMI_Update.vhd
-- Megafunction Name(s):
-- 			altremote_update
--
-- Simulation Library Files(s):
-- 			arriagx;lpm
-- ============================================================
-- ************************************************************
-- THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
--
-- 7.2 Build 151 09/26/2007 SJ Full Version
-- ************************************************************


--Copyright (C) 1991-2007 Altera Corporation
--Your use of Altera Corporation's design tools, logic functions 
--and other software and tools, and its AMPP partner logic 
--functions, and any output files from any of the foregoing 
--(including device programming or simulation files), and any 
--associated documentation or information are expressly subject 
--to the terms and conditions of the Altera Program License 
--Subscription Agreement, Altera MegaCore Function License 
--Agreement, or other applicable license agreement, including, 
--without limitation, that your use is for the sole purpose of 
--programming logic devices manufactured by Altera and sold by 
--Altera or its authorized distributors.  Please refer to the 
--applicable agreement for further details.


--altremote_update CBX_AUTO_BLACKBOX="ALL" DEVICE_FAMILY="Arria GX" operation_mode="active_serial_remote" sim_init_config="factory" sim_init_page_select=0 sim_init_status=13 sim_init_watchdog_value=1 busy clock data_in data_out param read_param reconfig reset reset_timer write_param
--VERSION_BEGIN 7.2 cbx_altremote_update 2007:07:25:16:51:00:SJ cbx_cycloneii 2007:06:13:15:47:32:SJ cbx_lpm_add_sub 2007:08:06:16:01:34:SJ cbx_lpm_compare 2007:06:21:15:54:06:SJ cbx_lpm_counter 2007:08:07:01:40:08:SJ cbx_lpm_decode 2007:03:12:19:01:52:SJ cbx_mgl 2007:08:03:15:48:12:SJ cbx_stratix 2007:05:02:16:27:14:SJ cbx_stratixii 2007:06:28:17:26:26:SJ  VERSION_END


--------------------------------------------------------------------------------
--$Rev:: 1394                                                                  $
--$Author:: Quirin                                                             $
--$Date:: 2010-04-07 15:08:25 +0200 (Mi., 07 Apr 2010)                         $
--------------------------------------------------------------------------------

 LIBRARY arriagx;
 USE arriagx.all;

 LIBRARY lpm;
 USE lpm.all;

--synthesis_resources = arriagx_rublock 1 lpm_counter 2 reg 29 
 LIBRARY ieee;
 USE ieee.std_logic_1164.all;

 ENTITY  ASMI_Update_rmtupdt_unq IS 
	 PORT 
	 ( 
		 busy	:	OUT  STD_LOGIC;
		 clock	:	IN  STD_LOGIC;
		 data_in	:	IN  STD_LOGIC_VECTOR (11 DOWNTO 0) := (OTHERS => '0');
		 data_out	:	OUT  STD_LOGIC_VECTOR (11 DOWNTO 0);
		 param	:	IN  STD_LOGIC_VECTOR (2 DOWNTO 0) := (OTHERS => '0');
		 read_param	:	IN  STD_LOGIC := '0';
		 reconfig	:	IN  STD_LOGIC := '0';
		 reset	:	IN  STD_LOGIC;
		 reset_timer	:	IN  STD_LOGIC := '0';
		 write_param	:	IN  STD_LOGIC := '0'
	 ); 
 END ASMI_Update_rmtupdt_unq;

 ARCHITECTURE RTL OF ASMI_Update_rmtupdt_unq IS

	 ATTRIBUTE synthesis_clearbox : boolean;
	 ATTRIBUTE synthesis_clearbox OF RTL : ARCHITECTURE IS true;
	 ATTRIBUTE ALTERA_ATTRIBUTE : string;
	 ATTRIBUTE ALTERA_ATTRIBUTE OF RTL : ARCHITECTURE IS "suppress_da_rule_internal=c104;suppress_da_rule_internal=C101";

	 SIGNAL	 dffe10	:	STD_LOGIC
	 -- synopsys translate_off
	  := '0'
	 -- synopsys translate_on
	 ;
	 SIGNAL	 dffe11	:	STD_LOGIC
	 -- synopsys translate_off
	  := '0'
	 -- synopsys translate_on
	 ;
	 SIGNAL	 dffe12	:	STD_LOGIC
	 -- synopsys translate_off
	  := '0'
	 -- synopsys translate_on
	 ;
	 SIGNAL	 dffe13	:	STD_LOGIC
	 -- synopsys translate_off
	  := '0'
	 -- synopsys translate_on
	 ;
	 SIGNAL	 dffe14	:	STD_LOGIC
	 -- synopsys translate_off
	  := '0'
	 -- synopsys translate_on
	 ;
	 SIGNAL	 dffe15	:	STD_LOGIC
	 -- synopsys translate_off
	  := '0'
	 -- synopsys translate_on
	 ;
	 SIGNAL	 dffe16	:	STD_LOGIC
	 -- synopsys translate_off
	  := '0'
	 -- synopsys translate_on
	 ;
	 SIGNAL	 dffe17	:	STD_LOGIC
	 -- synopsys translate_off
	  := '0'
	 -- synopsys translate_on
	 ;
	 SIGNAL	 dffe18	:	STD_LOGIC
	 -- synopsys translate_off
	  := '0'
	 -- synopsys translate_on
	 ;
	 SIGNAL	 dffe19a	:	STD_LOGIC_VECTOR(2 DOWNTO 0)
	 -- synopsys translate_off
	  := (OTHERS => '0')
	 -- synopsys translate_on
	 ;
	 SIGNAL	 dffe4a	:	STD_LOGIC_VECTOR(11 DOWNTO 0)
	 -- synopsys translate_off
	  := "000000000000"
	 -- synopsys translate_on
	 ;
	 SIGNAL	 wire_dffe4a_clrn	:	STD_LOGIC_VECTOR(11 DOWNTO 0);
	 SIGNAL	 wire_dffe4a_ena	:	STD_LOGIC_VECTOR(11 DOWNTO 0);
	 SIGNAL	 dffe5	:	STD_LOGIC
	 -- synopsys translate_off
	  := '0'
	 -- synopsys translate_on
	 ;
	 SIGNAL	 dffe6	:	STD_LOGIC
	 -- synopsys translate_off
	  := '0'
	 -- synopsys translate_on
	 ;
	 SIGNAL	 dffe7	:	STD_LOGIC
	 -- synopsys translate_off
	  := '0'
	 -- synopsys translate_on
	 ;
	 SIGNAL	 dffe8	:	STD_LOGIC
	 -- synopsys translate_off
	  := '0'
	 -- synopsys translate_on
	 ;
	 SIGNAL	 dffe9	:	STD_LOGIC
	 -- synopsys translate_off
	  := '0'
	 -- synopsys translate_on
	 ;
	 SIGNAL  wire_cntr2_q	:	STD_LOGIC_VECTOR (4 DOWNTO 0);
	 SIGNAL  wire_cntr3_q	:	STD_LOGIC_VECTOR (3 DOWNTO 0);
	 SIGNAL  wire_sd1_regout	:	STD_LOGIC;
	 SIGNAL  wire_w_lg_w215w218w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_w215w227w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_w221w222w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_w_lg_idle261w262w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w230w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w225w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_w_lg_shift_reg_load_enable53w58w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_w_lg_shift_reg_load_enable53w94w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_w_lg_shift_reg_load_enable53w98w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_w_lg_shift_reg_load_enable53w62w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_w_lg_shift_reg_load_enable53w66w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_w_lg_shift_reg_load_enable53w70w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_w_lg_shift_reg_load_enable53w74w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_w_lg_shift_reg_load_enable53w78w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_w_lg_shift_reg_load_enable53w82w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_w_lg_shift_reg_load_enable53w86w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_w_lg_shift_reg_load_enable53w90w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_w_lg_shift_reg_load_enable53w54w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w215w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w221w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_idle261w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_read_data274w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_read_init_counter270w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_read_post280w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_read_pre_data269w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_rublock_regout_reg313w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_shift_reg_load_enable59w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_shift_reg_load_enable99w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_shift_reg_load_enable55w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_shift_reg_load_enable63w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_shift_reg_load_enable67w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_shift_reg_load_enable71w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_shift_reg_load_enable75w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_shift_reg_load_enable79w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_shift_reg_load_enable83w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_shift_reg_load_enable87w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_shift_reg_load_enable91w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_shift_reg_load_enable95w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_write_data289w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_write_init_counter286w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_write_post_data295w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_write_pre_data285w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_w_param_decoder_param_latch_range211w229w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_w_param_decoder_param_latch_range211w224w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_w_lg_shift_reg_clear50w51w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_bit_counter_all_done288w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_bit_counter_param_start_match268w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_clock303w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_idle244w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_read_data240w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_read_init243w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_read_init_counter242w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_read_param260w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_read_post239w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_read_pre_data241w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_select_shift_nloop312w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_shift_reg_load_enable53w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_width_counter_all_done272w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_width_counter_param_width_match273w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_write_data235w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_write_init238w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_write_init_counter237w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_write_load233w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_write_param259w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_write_post_data234w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_write_pre_data236w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_write_wait232w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_w_param_decoder_param_latch_range211w212w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_w_param_decoder_param_latch_range213w214w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_w_param_decoder_param_latch_range216w217w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_w_lg_w_lg_idle261w262w263w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_shift_reg_clear50w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_shift_reg_load_enable49w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  bit_counter_all_done :	STD_LOGIC;
	 SIGNAL  bit_counter_clear :	STD_LOGIC;
	 SIGNAL  bit_counter_enable :	STD_LOGIC;
	 SIGNAL  bit_counter_param_start :	STD_LOGIC_VECTOR (4 DOWNTO 0);
	 SIGNAL  bit_counter_param_start_match :	STD_LOGIC;
	 SIGNAL  idle :	STD_LOGIC;
	 SIGNAL  param_decoder_param_latch :	STD_LOGIC_VECTOR (2 DOWNTO 0);
	 SIGNAL  param_decoder_select :	STD_LOGIC_VECTOR (4 DOWNTO 0);
	 SIGNAL  power_up :	STD_LOGIC;
	 SIGNAL  read_data :	STD_LOGIC;
	 SIGNAL  read_init :	STD_LOGIC;
	 SIGNAL  read_init_counter :	STD_LOGIC;
	 SIGNAL  read_post :	STD_LOGIC;
	 SIGNAL  read_pre_data :	STD_LOGIC;
	 SIGNAL  rublock_captnupdt :	STD_LOGIC;
	 SIGNAL  rublock_clock :	STD_LOGIC;
	 SIGNAL  rublock_reconfig :	STD_LOGIC;
	 SIGNAL  rublock_regin :	STD_LOGIC;
	 SIGNAL  rublock_regout :	STD_LOGIC;
	 SIGNAL  rublock_regout_reg :	STD_LOGIC;
	 SIGNAL  rublock_shiftnld :	STD_LOGIC;
	 SIGNAL  select_shift_nloop :	STD_LOGIC;
	 SIGNAL  shift_reg_clear :	STD_LOGIC;
	 SIGNAL  shift_reg_load_enable :	STD_LOGIC;
	 SIGNAL  shift_reg_serial_in :	STD_LOGIC;
	 SIGNAL  shift_reg_serial_out :	STD_LOGIC;
	 SIGNAL  shift_reg_shift_enable :	STD_LOGIC;
	 SIGNAL  start_bit_decoder_out :	STD_LOGIC_VECTOR (4 DOWNTO 0);
	 SIGNAL  start_bit_decoder_param_select :	STD_LOGIC_VECTOR (4 DOWNTO 0);
	 SIGNAL  w102w :	STD_LOGIC_VECTOR (3 DOWNTO 0);
	 SIGNAL  w111w :	STD_LOGIC_VECTOR (3 DOWNTO 0);
	 SIGNAL  w121w :	STD_LOGIC_VECTOR (3 DOWNTO 0);
	 SIGNAL  w12w :	STD_LOGIC_VECTOR (4 DOWNTO 0);
	 SIGNAL  w132w :	STD_LOGIC_VECTOR (3 DOWNTO 0);
	 --SIGNAL  w141w :	STD_LOGIC_VECTOR (3 DOWNTO 0);
	 SIGNAL  w152w :	STD_LOGIC_VECTOR (4 DOWNTO 0);
	 SIGNAL  w165w :	STD_LOGIC_VECTOR (4 DOWNTO 0);
	 SIGNAL  w176w :	STD_LOGIC_VECTOR (4 DOWNTO 0);
	 SIGNAL  w187w :	STD_LOGIC_VECTOR (4 DOWNTO 0);
	 --SIGNAL  w199w :	STD_LOGIC_VECTOR (4 DOWNTO 0);
	 SIGNAL  w329w :	STD_LOGIC;
	 SIGNAL  w36w :	STD_LOGIC_VECTOR (3 DOWNTO 0);
	 SIGNAL  width_counter_all_done :	STD_LOGIC;
	 SIGNAL  width_counter_clear :	STD_LOGIC;
	 SIGNAL  width_counter_enable :	STD_LOGIC;
	 SIGNAL  width_counter_param_width :	STD_LOGIC_VECTOR (3 DOWNTO 0);
	 SIGNAL  width_counter_param_width_match :	STD_LOGIC;
	 SIGNAL  width_decoder_out :	STD_LOGIC_VECTOR (3 DOWNTO 0);
	 SIGNAL  width_decoder_param_select :	STD_LOGIC_VECTOR (4 DOWNTO 0);
	 SIGNAL  write_data :	STD_LOGIC;
	 SIGNAL  write_init :	STD_LOGIC;
	 SIGNAL  write_init_counter :	STD_LOGIC;
	 SIGNAL  write_load :	STD_LOGIC;
	 SIGNAL  write_post_data :	STD_LOGIC;
	 SIGNAL  write_pre_data :	STD_LOGIC;
	 SIGNAL  write_wait :	STD_LOGIC;
	 SIGNAL  wire_w_data_in_range57w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_data_in_range97w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_data_in_range52w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_data_in_range61w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_data_in_range65w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_data_in_range69w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_data_in_range73w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_data_in_range77w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_data_in_range81w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_data_in_range85w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_data_in_range89w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_data_in_range93w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_param_decoder_param_latch_range211w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_param_decoder_param_latch_range213w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_param_decoder_param_latch_range216w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 COMPONENT  lpm_counter
	 GENERIC 
	 (
		lpm_avalue	:	STRING := "0";
		lpm_direction	:	STRING := "DEFAULT";
		lpm_modulus	:	NATURAL := 0;
		lpm_port_updown	:	STRING := "PORT_CONNECTIVITY";
		lpm_pvalue	:	STRING := "0";
		lpm_svalue	:	STRING := "0";
		lpm_width	:	NATURAL;
		lpm_type	:	STRING := "lpm_counter"
	 );
	 PORT
	 ( 
		aclr	:	IN STD_LOGIC := '0';
		aload	:	IN STD_LOGIC := '0';
		aset	:	IN STD_LOGIC := '0';
		cin	:	IN STD_LOGIC := '1';
		clk_en	:	IN STD_LOGIC := '1';
		clock	:	IN STD_LOGIC;
		cnt_en	:	IN STD_LOGIC := '1';
		cout	:	OUT STD_LOGIC;
		data	:	IN STD_LOGIC_VECTOR(LPM_WIDTH-1 DOWNTO 0) := (OTHERS => '0');
		eq	:	OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
		q	:	OUT STD_LOGIC_VECTOR(LPM_WIDTH-1 DOWNTO 0);
		sclr	:	IN STD_LOGIC := '0';
		sload	:	IN STD_LOGIC := '0';
		sset	:	IN STD_LOGIC := '0';
		updown	:	IN STD_LOGIC := '1'
	 ); 
	 END COMPONENT;
	 COMPONENT  arriagx_rublock
	 GENERIC 
	 (
		operation_mode	:	STRING := "remote";
		sim_init_config	:	STRING := "factory";
		sim_init_page_select	:	NATURAL := 0;
		sim_init_status	:	NATURAL := 0;
		sim_init_watchdog_value	:	NATURAL := 0;
		lpm_type	:	STRING := "arriagx_rublock"
	 );
	 PORT
	 ( 
		captnupdt	:	IN STD_LOGIC;
		clk	:	IN STD_LOGIC;
		pgmout	:	OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
		rconfig	:	IN STD_LOGIC;
		regin	:	IN STD_LOGIC;
		regout	:	OUT STD_LOGIC;
		rsttimer	:	IN STD_LOGIC;
		shiftnld	:	IN STD_LOGIC
	 ); 
	 END COMPONENT;
 BEGIN

	wire_w_lg_w215w218w(0) <= wire_w215w(0) AND wire_w_lg_w_param_decoder_param_latch_range216w217w(0);
	wire_w_lg_w215w227w(0) <= wire_w215w(0) AND wire_w_param_decoder_param_latch_range216w(0);
	wire_w_lg_w221w222w(0) <= wire_w221w(0) AND wire_w_lg_w_param_decoder_param_latch_range216w217w(0);
	wire_w_lg_w_lg_idle261w262w(0) <= wire_w_lg_idle261w(0) AND wire_w_lg_write_param259w(0);
	wire_w230w(0) <= wire_w_lg_w_param_decoder_param_latch_range211w229w(0) AND wire_w_param_decoder_param_latch_range216w(0);
	wire_w225w(0) <= wire_w_lg_w_param_decoder_param_latch_range211w224w(0) AND wire_w_lg_w_param_decoder_param_latch_range216w217w(0);
	wire_w_lg_w_lg_shift_reg_load_enable53w58w(0) <= wire_w_lg_shift_reg_load_enable53w(0) AND dffe4a(1);
	wire_w_lg_w_lg_shift_reg_load_enable53w94w(0) <= wire_w_lg_shift_reg_load_enable53w(0) AND dffe4a(10);
	wire_w_lg_w_lg_shift_reg_load_enable53w98w(0) <= wire_w_lg_shift_reg_load_enable53w(0) AND dffe4a(11);
	wire_w_lg_w_lg_shift_reg_load_enable53w62w(0) <= wire_w_lg_shift_reg_load_enable53w(0) AND dffe4a(2);
	wire_w_lg_w_lg_shift_reg_load_enable53w66w(0) <= wire_w_lg_shift_reg_load_enable53w(0) AND dffe4a(3);
	wire_w_lg_w_lg_shift_reg_load_enable53w70w(0) <= wire_w_lg_shift_reg_load_enable53w(0) AND dffe4a(4);
	wire_w_lg_w_lg_shift_reg_load_enable53w74w(0) <= wire_w_lg_shift_reg_load_enable53w(0) AND dffe4a(5);
	wire_w_lg_w_lg_shift_reg_load_enable53w78w(0) <= wire_w_lg_shift_reg_load_enable53w(0) AND dffe4a(6);
	wire_w_lg_w_lg_shift_reg_load_enable53w82w(0) <= wire_w_lg_shift_reg_load_enable53w(0) AND dffe4a(7);
	wire_w_lg_w_lg_shift_reg_load_enable53w86w(0) <= wire_w_lg_shift_reg_load_enable53w(0) AND dffe4a(8);
	wire_w_lg_w_lg_shift_reg_load_enable53w90w(0) <= wire_w_lg_shift_reg_load_enable53w(0) AND dffe4a(9);
	wire_w_lg_w_lg_shift_reg_load_enable53w54w(0) <= wire_w_lg_shift_reg_load_enable53w(0) AND shift_reg_serial_in;
	wire_w215w(0) <= wire_w_lg_w_param_decoder_param_latch_range211w212w(0) AND wire_w_lg_w_param_decoder_param_latch_range213w214w(0);
	wire_w221w(0) <= wire_w_lg_w_param_decoder_param_latch_range211w212w(0) AND wire_w_param_decoder_param_latch_range213w(0);
	wire_w_lg_idle261w(0) <= idle AND wire_w_lg_read_param260w(0);
	wire_w_lg_read_data274w(0) <= read_data AND wire_w_lg_width_counter_param_width_match273w(0);
	wire_w_lg_read_init_counter270w(0) <= read_init_counter AND wire_w_lg_bit_counter_param_start_match268w(0);
	wire_w_lg_read_post280w(0) <= read_post AND wire_w_lg_width_counter_all_done272w(0);
	wire_w_lg_read_pre_data269w(0) <= read_pre_data AND wire_w_lg_bit_counter_param_start_match268w(0);
	wire_w_lg_rublock_regout_reg313w(0) <= rublock_regout_reg AND wire_w_lg_select_shift_nloop312w(0);
	wire_w_lg_shift_reg_load_enable59w(0) <= shift_reg_load_enable AND wire_w_data_in_range57w(0);
	wire_w_lg_shift_reg_load_enable99w(0) <= shift_reg_load_enable AND wire_w_data_in_range97w(0);
	wire_w_lg_shift_reg_load_enable55w(0) <= shift_reg_load_enable AND wire_w_data_in_range52w(0);
	wire_w_lg_shift_reg_load_enable63w(0) <= shift_reg_load_enable AND wire_w_data_in_range61w(0);
	wire_w_lg_shift_reg_load_enable67w(0) <= shift_reg_load_enable AND wire_w_data_in_range65w(0);
	wire_w_lg_shift_reg_load_enable71w(0) <= shift_reg_load_enable AND wire_w_data_in_range69w(0);
	wire_w_lg_shift_reg_load_enable75w(0) <= shift_reg_load_enable AND wire_w_data_in_range73w(0);
	wire_w_lg_shift_reg_load_enable79w(0) <= shift_reg_load_enable AND wire_w_data_in_range77w(0);
	wire_w_lg_shift_reg_load_enable83w(0) <= shift_reg_load_enable AND wire_w_data_in_range81w(0);
	wire_w_lg_shift_reg_load_enable87w(0) <= shift_reg_load_enable AND wire_w_data_in_range85w(0);
	wire_w_lg_shift_reg_load_enable91w(0) <= shift_reg_load_enable AND wire_w_data_in_range89w(0);
	wire_w_lg_shift_reg_load_enable95w(0) <= shift_reg_load_enable AND wire_w_data_in_range93w(0);
	wire_w_lg_write_data289w(0) <= write_data AND wire_w_lg_width_counter_param_width_match273w(0);
	wire_w_lg_write_init_counter286w(0) <= write_init_counter AND wire_w_lg_bit_counter_param_start_match268w(0);
	wire_w_lg_write_post_data295w(0) <= write_post_data AND wire_w_lg_bit_counter_all_done288w(0);
	wire_w_lg_write_pre_data285w(0) <= write_pre_data AND wire_w_lg_bit_counter_param_start_match268w(0);
	wire_w_lg_w_param_decoder_param_latch_range211w229w(0) <= wire_w_param_decoder_param_latch_range211w(0) AND wire_w_lg_w_param_decoder_param_latch_range213w214w(0);
	wire_w_lg_w_param_decoder_param_latch_range211w224w(0) <= wire_w_param_decoder_param_latch_range211w(0) AND wire_w_param_decoder_param_latch_range213w(0);
	wire_w_lg_w_lg_shift_reg_clear50w51w(0) <= NOT wire_w_lg_shift_reg_clear50w(0);
	wire_w_lg_bit_counter_all_done288w(0) <= NOT bit_counter_all_done;
	wire_w_lg_bit_counter_param_start_match268w(0) <= NOT bit_counter_param_start_match;
	wire_w_lg_clock303w(0) <= NOT clock;
	wire_w_lg_idle244w(0) <= NOT idle;
	wire_w_lg_read_data240w(0) <= NOT read_data;
	wire_w_lg_read_init243w(0) <= NOT read_init;
	wire_w_lg_read_init_counter242w(0) <= NOT read_init_counter;
	wire_w_lg_read_param260w(0) <= NOT read_param;
	wire_w_lg_read_post239w(0) <= NOT read_post;
	wire_w_lg_read_pre_data241w(0) <= NOT read_pre_data;
	wire_w_lg_select_shift_nloop312w(0) <= NOT select_shift_nloop;
	wire_w_lg_shift_reg_load_enable53w(0) <= NOT shift_reg_load_enable;
	wire_w_lg_width_counter_all_done272w(0) <= NOT width_counter_all_done;
	wire_w_lg_width_counter_param_width_match273w(0) <= NOT width_counter_param_width_match;
	wire_w_lg_write_data235w(0) <= NOT write_data;
	wire_w_lg_write_init238w(0) <= NOT write_init;
	wire_w_lg_write_init_counter237w(0) <= NOT write_init_counter;
	wire_w_lg_write_load233w(0) <= NOT write_load;
	wire_w_lg_write_param259w(0) <= NOT write_param;
	wire_w_lg_write_post_data234w(0) <= NOT write_post_data;
	wire_w_lg_write_pre_data236w(0) <= NOT write_pre_data;
	wire_w_lg_write_wait232w(0) <= NOT write_wait;
	wire_w_lg_w_param_decoder_param_latch_range211w212w(0) <= NOT wire_w_param_decoder_param_latch_range211w(0);
	wire_w_lg_w_param_decoder_param_latch_range213w214w(0) <= NOT wire_w_param_decoder_param_latch_range213w(0);
	wire_w_lg_w_param_decoder_param_latch_range216w217w(0) <= NOT wire_w_param_decoder_param_latch_range216w(0);
	wire_w_lg_w_lg_w_lg_idle261w262w263w(0) <= wire_w_lg_w_lg_idle261w262w(0) OR write_wait;
	wire_w_lg_shift_reg_clear50w(0) <= shift_reg_clear OR reset;
	wire_w_lg_shift_reg_load_enable49w(0) <= shift_reg_load_enable OR shift_reg_shift_enable;
	bit_counter_all_done <= (((((NOT wire_cntr2_q(0)) AND wire_cntr2_q(1)) AND (NOT wire_cntr2_q(2))) AND wire_cntr2_q(3)) AND wire_cntr2_q(4));
	bit_counter_clear <= (read_init OR write_init);
	bit_counter_enable <= (((((((((read_init OR write_init) OR read_init_counter) OR write_init_counter) OR read_pre_data) OR write_pre_data) OR read_data) OR write_data) OR read_post) OR write_post_data);
	bit_counter_param_start <= start_bit_decoder_out;
	bit_counter_param_start_match <= (((((NOT w12w(0)) AND (NOT w12w(1))) AND (NOT w12w(2))) AND (NOT w12w(3))) AND (NOT w12w(4)));
	busy <= wire_w_lg_idle244w(0);
	data_out <= dffe4a;
	idle <= dffe5;
	param_decoder_param_latch <= dffe19a;
	param_decoder_select <= ( wire_w230w & wire_w_lg_w215w227w & wire_w225w & wire_w_lg_w221w222w & wire_w_lg_w215w218w);
	power_up <= ((((((((((((wire_w_lg_idle244w(0) AND wire_w_lg_read_init243w(0)) AND wire_w_lg_read_init_counter242w(0)) AND wire_w_lg_read_pre_data241w(0)) AND wire_w_lg_read_data240w(0)) AND wire_w_lg_read_post239w(0)) AND wire_w_lg_write_init238w(0)) AND wire_w_lg_write_init_counter237w(0)) AND wire_w_lg_write_pre_data236w(0)) AND wire_w_lg_write_data235w(0)) AND wire_w_lg_write_post_data234w(0)) AND wire_w_lg_write_load233w(0)) AND wire_w_lg_write_wait232w(0));
	read_data <= dffe9;
	read_init <= dffe6;
	read_init_counter <= dffe7;
	read_post <= dffe10;
	read_pre_data <= dffe8;
	rublock_captnupdt <= wire_w_lg_write_load233w(0);
	rublock_clock <= ((wire_w_lg_clock303w(0) AND wire_w_lg_idle244w(0)) AND wire_w_lg_write_wait232w(0));
	rublock_reconfig <= (idle AND reconfig);
	rublock_regin <= (wire_w_lg_rublock_regout_reg313w(0) OR (shift_reg_serial_out AND select_shift_nloop));
	rublock_regout <= wire_sd1_regout;
	rublock_regout_reg <= dffe18;
	rublock_shiftnld <= (((((read_pre_data OR write_pre_data) OR read_data) OR write_data) OR read_post) OR write_post_data);
	select_shift_nloop <= (wire_w_lg_read_data274w(0) OR wire_w_lg_write_data289w(0));
	shift_reg_clear <= read_init;
	shift_reg_load_enable <= (idle AND write_param);
	shift_reg_serial_in <= (rublock_regout_reg AND select_shift_nloop);
	shift_reg_serial_out <= dffe4a(0);
	shift_reg_shift_enable <= (((read_data OR write_data) OR read_post) OR write_post_data);
	start_bit_decoder_out <= ((((w152w OR w165w) OR w176w) OR w187w) OR ( "0" & "0" & start_bit_decoder_param_select(4) & "0" & start_bit_decoder_param_select(4)));
	start_bit_decoder_param_select <= param_decoder_select;
	w102w <= ( "0" & width_decoder_param_select(0) & "0" & width_decoder_param_select(0));
	w111w <= ( width_decoder_param_select(1) & width_decoder_param_select(1) & "0" & "0");
	w121w <= ( "0" & "0" & "0" & width_decoder_param_select(2));
	w12w <= (wire_cntr2_q XOR bit_counter_param_start);
	w132w <= ( "0" & width_decoder_param_select(3) & width_decoder_param_select(3) & width_decoder_param_select(3));
	--w141w <= ( "0" & "0" & "0" & width_decoder_param_select(4));
	w152w <= ( "0" & "0" & "0" & "0" & "0");
	w165w <= ( "0" & start_bit_decoder_param_select(1) & start_bit_decoder_param_select(1) & start_bit_decoder_param_select(1) & "0");
	w176w <= ( "0" & start_bit_decoder_param_select(2) & start_bit_decoder_param_select(2) & "0" & start_bit_decoder_param_select(2));
	w187w <= ( "0" & "0" & start_bit_decoder_param_select(3) & start_bit_decoder_param_select(3) & "0");
	--w199w <= ( "0" & "0" & start_bit_decoder_param_select(4) & "0" & start_bit_decoder_param_select(4));
	w329w <= (idle AND (write_param OR read_param));
	w36w <= (wire_cntr3_q XOR width_counter_param_width);
	width_counter_all_done <= (((wire_cntr3_q(0) AND wire_cntr3_q(1)) AND (NOT wire_cntr3_q(2))) AND wire_cntr3_q(3));
	width_counter_clear <= (read_init OR write_init);
	width_counter_enable <= ((read_data OR write_data) OR read_post);
	width_counter_param_width <= width_decoder_out;
	width_counter_param_width_match <= ((((NOT w36w(0)) AND (NOT w36w(1))) AND (NOT w36w(2))) AND (NOT w36w(3)));
	width_decoder_out <= ((((w102w OR w111w) OR w121w) OR w132w) OR ( "0" & "0" & "0" & width_decoder_param_select(4)));
	width_decoder_param_select <= param_decoder_select;
	write_data <= dffe14;
	write_init <= dffe11;
	write_init_counter <= dffe12;
	write_load <= dffe16;
	write_post_data <= dffe15;
	write_pre_data <= dffe13;
	write_wait <= dffe17;
	wire_w_data_in_range57w(0) <= data_in(0);
	wire_w_data_in_range97w(0) <= data_in(10);
	wire_w_data_in_range52w(0) <= data_in(11);
	wire_w_data_in_range61w(0) <= data_in(1);
	wire_w_data_in_range65w(0) <= data_in(2);
	wire_w_data_in_range69w(0) <= data_in(3);
	wire_w_data_in_range73w(0) <= data_in(4);
	wire_w_data_in_range77w(0) <= data_in(5);
	wire_w_data_in_range81w(0) <= data_in(6);
	wire_w_data_in_range85w(0) <= data_in(7);
	wire_w_data_in_range89w(0) <= data_in(8);
	wire_w_data_in_range93w(0) <= data_in(9);
	wire_w_param_decoder_param_latch_range211w(0) <= param_decoder_param_latch(0);
	wire_w_param_decoder_param_latch_range213w(0) <= param_decoder_param_latch(1);
	wire_w_param_decoder_param_latch_range216w(0) <= param_decoder_param_latch(2);
	PROCESS (clock, reset)
	BEGIN
		IF (reset = '1') THEN dffe10 <= '0';
		ELSIF (clock = '1' AND clock'event) THEN dffe10 <= (((read_data AND width_counter_param_width_match) AND wire_w_lg_width_counter_all_done272w(0)) OR wire_w_lg_read_post280w(0));
		END IF;
	END PROCESS;
	PROCESS (clock, reset)
	BEGIN
		IF (reset = '1') THEN dffe11 <= '0';
		ELSIF (clock = '1' AND clock'event) THEN dffe11 <= (idle AND write_param);
		END IF;
	END PROCESS;
	PROCESS (clock, reset)
	BEGIN
		IF (reset = '1') THEN dffe12 <= '0';
		ELSIF (clock = '1' AND clock'event) THEN dffe12 <= write_init;
		END IF;
	END PROCESS;
	PROCESS (clock, reset)
	BEGIN
		IF (reset = '1') THEN dffe13 <= '0';
		ELSIF (clock = '1' AND clock'event) THEN dffe13 <= (wire_w_lg_write_init_counter286w(0) OR wire_w_lg_write_pre_data285w(0));
		END IF;
	END PROCESS;
	PROCESS (clock, reset)
	BEGIN
		IF (reset = '1') THEN dffe14 <= '0';
		ELSIF (clock = '1' AND clock'event) THEN dffe14 <= (((write_init_counter AND bit_counter_param_start_match) OR (write_pre_data AND bit_counter_param_start_match)) OR (wire_w_lg_write_data289w(0) AND wire_w_lg_bit_counter_all_done288w(0)));
		END IF;
	END PROCESS;
	PROCESS (clock, reset)
	BEGIN
		IF (reset = '1') THEN dffe15 <= '0';
		ELSIF (clock = '1' AND clock'event) THEN dffe15 <= (((write_data AND width_counter_param_width_match) AND wire_w_lg_bit_counter_all_done288w(0)) OR wire_w_lg_write_post_data295w(0));
		END IF;
	END PROCESS;
	PROCESS (clock, reset)
	BEGIN
		IF (reset = '1') THEN dffe16 <= '0';
		ELSIF (clock = '1' AND clock'event) THEN dffe16 <= ((write_data AND bit_counter_all_done) OR (write_post_data AND bit_counter_all_done));
		END IF;
	END PROCESS;
	PROCESS (clock, reset)
	BEGIN
		IF (reset = '1') THEN dffe17 <= '0';
		ELSIF (clock = '1' AND clock'event) THEN dffe17 <= write_load;
		END IF;
	END PROCESS;
	PROCESS (clock, reset)
	BEGIN
		IF (reset = '1') THEN dffe18 <= '0';
		ELSIF (clock = '1' AND clock'event) THEN dffe18 <= rublock_regout;
		END IF;
	END PROCESS;
	PROCESS (clock, reset)
	BEGIN
		IF (reset = '1') THEN dffe19a <= (OTHERS => '0');
		ELSIF (clock = '1' AND clock'event) THEN 
			IF (w329w = '1') THEN dffe19a <= param;
			END IF;
		END IF;
	END PROCESS;
	PROCESS (clock, wire_dffe4a_clrn(0))
	BEGIN
		IF (wire_dffe4a_clrn(0) = '0') THEN dffe4a(0) <= '0';
		ELSIF (clock = '1' AND clock'event) THEN 
			IF (wire_dffe4a_ena(0) = '1') THEN dffe4a(0) <= (wire_w_lg_shift_reg_load_enable59w(0) OR wire_w_lg_w_lg_shift_reg_load_enable53w58w(0));
			END IF;
		END IF;
	END PROCESS;
	PROCESS (clock, wire_dffe4a_clrn(1))
	BEGIN
		IF (wire_dffe4a_clrn(1) = '0') THEN dffe4a(1) <= '0';
		ELSIF (clock = '1' AND clock'event) THEN 
			IF (wire_dffe4a_ena(1) = '1') THEN dffe4a(1) <= (wire_w_lg_shift_reg_load_enable63w(0) OR wire_w_lg_w_lg_shift_reg_load_enable53w62w(0));
			END IF;
		END IF;
	END PROCESS;
	PROCESS (clock, wire_dffe4a_clrn(2))
	BEGIN
		IF (wire_dffe4a_clrn(2) = '0') THEN dffe4a(2) <= '0';
		ELSIF (clock = '1' AND clock'event) THEN 
			IF (wire_dffe4a_ena(2) = '1') THEN dffe4a(2) <= (wire_w_lg_shift_reg_load_enable67w(0) OR wire_w_lg_w_lg_shift_reg_load_enable53w66w(0));
			END IF;
		END IF;
	END PROCESS;
	PROCESS (clock, wire_dffe4a_clrn(3))
	BEGIN
		IF (wire_dffe4a_clrn(3) = '0') THEN dffe4a(3) <= '0';
		ELSIF (clock = '1' AND clock'event) THEN 
			IF (wire_dffe4a_ena(3) = '1') THEN dffe4a(3) <= (wire_w_lg_shift_reg_load_enable71w(0) OR wire_w_lg_w_lg_shift_reg_load_enable53w70w(0));
			END IF;
		END IF;
	END PROCESS;
	PROCESS (clock, wire_dffe4a_clrn(4))
	BEGIN
		IF (wire_dffe4a_clrn(4) = '0') THEN dffe4a(4) <= '0';
		ELSIF (clock = '1' AND clock'event) THEN 
			IF (wire_dffe4a_ena(4) = '1') THEN dffe4a(4) <= (wire_w_lg_shift_reg_load_enable75w(0) OR wire_w_lg_w_lg_shift_reg_load_enable53w74w(0));
			END IF;
		END IF;
	END PROCESS;
	PROCESS (clock, wire_dffe4a_clrn(5))
	BEGIN
		IF (wire_dffe4a_clrn(5) = '0') THEN dffe4a(5) <= '0';
		ELSIF (clock = '1' AND clock'event) THEN 
			IF (wire_dffe4a_ena(5) = '1') THEN dffe4a(5) <= (wire_w_lg_shift_reg_load_enable79w(0) OR wire_w_lg_w_lg_shift_reg_load_enable53w78w(0));
			END IF;
		END IF;
	END PROCESS;
	PROCESS (clock, wire_dffe4a_clrn(6))
	BEGIN
		IF (wire_dffe4a_clrn(6) = '0') THEN dffe4a(6) <= '0';
		ELSIF (clock = '1' AND clock'event) THEN 
			IF (wire_dffe4a_ena(6) = '1') THEN dffe4a(6) <= (wire_w_lg_shift_reg_load_enable83w(0) OR wire_w_lg_w_lg_shift_reg_load_enable53w82w(0));
			END IF;
		END IF;
	END PROCESS;
	PROCESS (clock, wire_dffe4a_clrn(7))
	BEGIN
		IF (wire_dffe4a_clrn(7) = '0') THEN dffe4a(7) <= '0';
		ELSIF (clock = '1' AND clock'event) THEN 
			IF (wire_dffe4a_ena(7) = '1') THEN dffe4a(7) <= (wire_w_lg_shift_reg_load_enable87w(0) OR wire_w_lg_w_lg_shift_reg_load_enable53w86w(0));
			END IF;
		END IF;
	END PROCESS;
	PROCESS (clock, wire_dffe4a_clrn(8))
	BEGIN
		IF (wire_dffe4a_clrn(8) = '0') THEN dffe4a(8) <= '0';
		ELSIF (clock = '1' AND clock'event) THEN 
			IF (wire_dffe4a_ena(8) = '1') THEN dffe4a(8) <= (wire_w_lg_shift_reg_load_enable91w(0) OR wire_w_lg_w_lg_shift_reg_load_enable53w90w(0));
			END IF;
		END IF;
	END PROCESS;
	PROCESS (clock, wire_dffe4a_clrn(9))
	BEGIN
		IF (wire_dffe4a_clrn(9) = '0') THEN dffe4a(9) <= '0';
		ELSIF (clock = '1' AND clock'event) THEN 
			IF (wire_dffe4a_ena(9) = '1') THEN dffe4a(9) <= (wire_w_lg_shift_reg_load_enable95w(0) OR wire_w_lg_w_lg_shift_reg_load_enable53w94w(0));
			END IF;
		END IF;
	END PROCESS;
	PROCESS (clock, wire_dffe4a_clrn(10))
	BEGIN
		IF (wire_dffe4a_clrn(10) = '0') THEN dffe4a(10) <= '0';
		ELSIF (clock = '1' AND clock'event) THEN 
			IF (wire_dffe4a_ena(10) = '1') THEN dffe4a(10) <= (wire_w_lg_shift_reg_load_enable99w(0) OR wire_w_lg_w_lg_shift_reg_load_enable53w98w(0));
			END IF;
		END IF;
	END PROCESS;
	PROCESS (clock, wire_dffe4a_clrn(11))
	BEGIN
		IF (wire_dffe4a_clrn(11) = '0') THEN dffe4a(11) <= '0';
		ELSIF (clock = '1' AND clock'event) THEN 
			IF (wire_dffe4a_ena(11) = '1') THEN dffe4a(11) <= (wire_w_lg_shift_reg_load_enable55w(0) OR wire_w_lg_w_lg_shift_reg_load_enable53w54w(0));
			END IF;
		END IF;
	END PROCESS;
	loop51 : FOR i IN 0 TO 11 GENERATE
		wire_dffe4a_clrn(i) <= wire_w_lg_w_lg_shift_reg_clear50w51w(0);
	END GENERATE loop51;
	loop52 : FOR i IN 0 TO 11 GENERATE
		wire_dffe4a_ena(i) <= wire_w_lg_shift_reg_load_enable49w(0);
	END GENERATE loop52;
	PROCESS (clock, reset)
	BEGIN
		IF (reset = '1') THEN dffe5 <= '1';
		ELSIF (clock = '1' AND clock'event) THEN dffe5 <= (((wire_w_lg_w_lg_w_lg_idle261w262w263w(0) OR (read_data AND width_counter_all_done)) OR (read_post AND width_counter_all_done)) OR power_up);
		END IF;
	END PROCESS;
	PROCESS (clock, reset)
	BEGIN
		IF (reset = '1') THEN dffe6 <= '0';
		ELSIF (clock = '1' AND clock'event) THEN dffe6 <= (idle AND read_param);
		END IF;
	END PROCESS;
	PROCESS (clock, reset)
	BEGIN
		IF (reset = '1') THEN dffe7 <= '0';
		ELSIF (clock = '1' AND clock'event) THEN dffe7 <= read_init;
		END IF;
	END PROCESS;
	PROCESS (clock, reset)
	BEGIN
		IF (reset = '1') THEN dffe8 <= '0';
		ELSIF (clock = '1' AND clock'event) THEN dffe8 <= (wire_w_lg_read_init_counter270w(0) OR wire_w_lg_read_pre_data269w(0));
		END IF;
	END PROCESS;
	PROCESS (clock, reset)
	BEGIN
		IF (reset = '1') THEN dffe9 <= '0';
		ELSIF (clock = '1' AND clock'event) THEN dffe9 <= (((read_init_counter AND bit_counter_param_start_match) OR (read_pre_data AND bit_counter_param_start_match)) OR (wire_w_lg_read_data274w(0) AND wire_w_lg_width_counter_all_done272w(0)));
		END IF;
	END PROCESS;
	cntr2 :  lpm_counter
	  GENERIC MAP (
		lpm_direction => "UP",
		lpm_port_updown => "PORT_UNUSED",
		lpm_width => 5
	  )
	  PORT MAP ( 
		clock => clock,
		cnt_en => bit_counter_enable,
		q => wire_cntr2_q,
		sclr => bit_counter_clear
	  );
	cntr3 :  lpm_counter
	  GENERIC MAP (
		lpm_direction => "UP",
		lpm_port_updown => "PORT_UNUSED",
		lpm_width => 4
	  )
	  PORT MAP ( 
		clock => clock,
		cnt_en => width_counter_enable,
		q => wire_cntr3_q,
		sclr => width_counter_clear
	  );
	sd1 :  arriagx_rublock
	  GENERIC MAP (
		operation_mode => "active_serial_remote",
		sim_init_config => "factory",
		sim_init_page_select => 0,
		sim_init_status => 13,
		sim_init_watchdog_value => 1
	  )
	  PORT MAP ( 
		captnupdt => rublock_captnupdt,
		clk => rublock_clock,
		rconfig => rublock_reconfig,
		regin => rublock_regin,
		regout => wire_sd1_regout,
		rsttimer => reset_timer,
		shiftnld => rublock_shiftnld
	  );

 END RTL; --ASMI_Update_rmtupdt_unq
--VALID FILE


LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY ASMI_Update IS
	PORT
	(
		clock		: IN STD_LOGIC ;
		data_in		: IN STD_LOGIC_VECTOR (11 DOWNTO 0);
		param		: IN STD_LOGIC_VECTOR (2 DOWNTO 0);
		read_param		: IN STD_LOGIC ;
		reconfig		: IN STD_LOGIC ;
		reset		: IN STD_LOGIC ;
		reset_timer		: IN STD_LOGIC ;
		write_param		: IN STD_LOGIC ;
		busy		: OUT STD_LOGIC ;
		data_out		: OUT STD_LOGIC_VECTOR (11 DOWNTO 0)
	);
END ASMI_Update;


ARCHITECTURE RTL OF asmi_update IS

	ATTRIBUTE synthesis_clearbox: boolean;
	ATTRIBUTE synthesis_clearbox OF RTL: ARCHITECTURE IS TRUE;
	SIGNAL sub_wire0	: STD_LOGIC ;
	SIGNAL sub_wire1	: STD_LOGIC_VECTOR (11 DOWNTO 0);



	COMPONENT ASMI_Update_rmtupdt_unq
	PORT (
			reconfig	: IN STD_LOGIC ;
			param	: IN STD_LOGIC_VECTOR (2 DOWNTO 0);
			reset_timer	: IN STD_LOGIC ;
			read_param	: IN STD_LOGIC ;
			reset	: IN STD_LOGIC ;
			data_in	: IN STD_LOGIC_VECTOR (11 DOWNTO 0);
			busy	: OUT STD_LOGIC ;
			clock	: IN STD_LOGIC ;
			data_out	: OUT STD_LOGIC_VECTOR (11 DOWNTO 0);
			write_param	: IN STD_LOGIC 
	);
	END COMPONENT;

BEGIN
	busy    <= sub_wire0;
	data_out    <= sub_wire1(11 DOWNTO 0);

	ASMI_Update_rmtupdt_unq_component : ASMI_Update_rmtupdt_unq
	PORT MAP (
		reconfig => reconfig,
		param => param,
		reset_timer => reset_timer,
		read_param => read_param,
		reset => reset,
		data_in => data_in,
		clock => clock,
		write_param => write_param,
		busy => sub_wire0,
		data_out => sub_wire1
	);



END RTL;

-- ============================================================
-- CNX file retrieval info
-- ============================================================
-- Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Arria GX"
-- Retrieval info: PRIVATE: SIM_INIT_CONFIG_COMBO STRING "FACTORY"
-- Retrieval info: PRIVATE: SIM_INIT_PAGE_SELECT_COMBO STRING "0"
-- Retrieval info: PRIVATE: SIM_INIT_STAT_BIT0_CHECK STRING "1"
-- Retrieval info: PRIVATE: SIM_INIT_STAT_BIT1_CHECK STRING "0"
-- Retrieval info: PRIVATE: SIM_INIT_STAT_BIT2_CHECK STRING "1"
-- Retrieval info: PRIVATE: SIM_INIT_STAT_BIT3_CHECK STRING "1"
-- Retrieval info: PRIVATE: SIM_INIT_STAT_BIT4_CHECK STRING "1"
-- Retrieval info: PRIVATE: SIM_INIT_WATCHDOG_VALUE_EDIT STRING "1"
-- Retrieval info: PRIVATE: SUPPORT_WRITE_CHECK STRING "1"
-- Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "0"
-- Retrieval info: PRIVATE: WATCHDOG_ENABLE_CHECK STRING "1"
-- Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Arria GX"
-- Retrieval info: CONSTANT: OPERATION_MODE STRING "ACTIVE_SERIAL_REMOTE"
-- Retrieval info: CONSTANT: SIM_INIT_CONFIG STRING "FACTORY"
-- Retrieval info: CONSTANT: SIM_INIT_PAGE_SELECT NUMERIC "0"
-- Retrieval info: CONSTANT: SIM_INIT_STATUS NUMERIC "13"
-- Retrieval info: CONSTANT: SIM_INIT_WATCHDOG_VALUE NUMERIC "1"
-- Retrieval info: USED_PORT: busy 0 0 0 0 OUTPUT NODEFVAL "busy"
-- Retrieval info: USED_PORT: clock 0 0 0 0 INPUT NODEFVAL "clock"
-- Retrieval info: USED_PORT: data_in 0 0 12 0 INPUT NODEFVAL "data_in[11..0]"
-- Retrieval info: USED_PORT: data_out 0 0 12 0 OUTPUT NODEFVAL "data_out[11..0]"
-- Retrieval info: USED_PORT: param 0 0 3 0 INPUT NODEFVAL "param[2..0]"
-- Retrieval info: USED_PORT: read_param 0 0 0 0 INPUT NODEFVAL "read_param"
-- Retrieval info: USED_PORT: reconfig 0 0 0 0 INPUT NODEFVAL "reconfig"
-- Retrieval info: USED_PORT: reset 0 0 0 0 INPUT NODEFVAL "reset"
-- Retrieval info: USED_PORT: reset_timer 0 0 0 0 INPUT NODEFVAL "reset_timer"
-- Retrieval info: USED_PORT: write_param 0 0 0 0 INPUT NODEFVAL "write_param"
-- Retrieval info: CONNECT: @data_in 0 0 12 0 data_in 0 0 12 0
-- Retrieval info: CONNECT: @reset_timer 0 0 0 0 reset_timer 0 0 0 0
-- Retrieval info: CONNECT: @reset 0 0 0 0 reset 0 0 0 0
-- Retrieval info: CONNECT: @read_param 0 0 0 0 read_param 0 0 0 0
-- Retrieval info: CONNECT: @write_param 0 0 0 0 write_param 0 0 0 0
-- Retrieval info: CONNECT: data_out 0 0 12 0 @data_out 0 0 12 0
-- Retrieval info: CONNECT: @clock 0 0 0 0 clock 0 0 0 0
-- Retrieval info: CONNECT: @param 0 0 3 0 param 0 0 3 0
-- Retrieval info: CONNECT: busy 0 0 0 0 @busy 0 0 0 0
-- Retrieval info: CONNECT: @reconfig 0 0 0 0 reconfig 0 0 0 0
-- Retrieval info: GEN_FILE: TYPE_NORMAL ASMI_Update.vhd TRUE FALSE
-- Retrieval info: GEN_FILE: TYPE_NORMAL ASMI_Update.inc FALSE FALSE
-- Retrieval info: GEN_FILE: TYPE_NORMAL ASMI_Update.cmp TRUE FALSE
-- Retrieval info: GEN_FILE: TYPE_NORMAL ASMI_Update.bsf TRUE FALSE
-- Retrieval info: GEN_FILE: TYPE_NORMAL ASMI_Update_inst.vhd TRUE FALSE
-- Retrieval info: LIB_FILE: arriagx
-- Retrieval info: LIB_FILE: lpm
