-- megafunction wizard: %Serial Flash Loader%
-- GENERATION: STANDARD
-- VERSION: WM1.0
-- MODULE: altserial_flash_loader 

-- ============================================================
-- File Name: ASMI_Bridge.vhd
-- Megafunction Name(s):
-- 			altserial_flash_loader
--
-- Simulation Library Files(s):
-- 			altera_mf
-- ============================================================
-- ************************************************************
-- THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
--
-- 7.2 Build 151 09/26/2007 SJ Full Version
-- ************************************************************


--Copyright (C) 1991-2007 Altera Corporation
--Your use of Altera Corporation's design tools, logic functions 
--and other software and tools, and its AMPP partner logic 
--functions, and any output files from any of the foregoing 
--(including device programming or simulation files), and any 
--associated documentation or information are expressly subject 
--to the terms and conditions of the Altera Program License 
--Subscription Agreement, Altera MegaCore Function License 
--Agreement, or other applicable license agreement, including, 
--without limitation, that your use is for the sole purpose of 
--programming logic devices manufactured by Altera and sold by 
--Altera or its authorized distributors.  Please refer to the 
--applicable agreement for further details.


--------------------------------------------------------------------------------
--$Rev:: 1394                                                                  $
--$Author:: Quirin                                                             $
--$Date:: 2010-04-07 15:08:25 +0200 (Mi., 07 Apr 2010)                         $
--------------------------------------------------------------------------------

LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY altera_mf;
USE altera_mf.all;

ENTITY ASMI_Bridge IS
	PORT
	(
		asdo_in		: IN STD_LOGIC ;
		asmi_access_granted		: IN STD_LOGIC ;
		dclk_in		: IN STD_LOGIC ;
		ncso_in		: IN STD_LOGIC ;
		noe_in		: IN STD_LOGIC ;
		asmi_access_request		: OUT STD_LOGIC ;
		data0_out		: OUT STD_LOGIC 
	);
END ASMI_Bridge;


ARCHITECTURE SYN OF asmi_bridge IS

	SIGNAL sub_wire0	: STD_LOGIC ;
	SIGNAL sub_wire1	: STD_LOGIC ;



	COMPONENT altserial_flash_loader
	GENERIC (
		enable_shared_access		: STRING;
		lpm_type		: STRING
	);
	PORT (
			scein	: IN STD_LOGIC ;
			dclkin	: IN STD_LOGIC ;
			data0out	: OUT STD_LOGIC ;
			sdoin	: IN STD_LOGIC ;
			asmi_access_granted	: IN STD_LOGIC ;
			asmi_access_request	: OUT STD_LOGIC ;
			noe	: IN STD_LOGIC 
	);
	END COMPONENT;

BEGIN
	data0_out    <= sub_wire0;
	asmi_access_request    <= sub_wire1;

	altserial_flash_loader_component : altserial_flash_loader
	GENERIC MAP (
		enable_shared_access => "ON",
		lpm_type => "altserial_flash_loader"
	)
	PORT MAP (
		scein => ncso_in,
		dclkin => dclk_in,
		sdoin => asdo_in,
		asmi_access_granted => asmi_access_granted,
		noe => noe_in,
		data0out => sub_wire0,
		asmi_access_request => sub_wire1
	);



END SYN;

-- ============================================================
-- CNX file retrieval info
-- ============================================================
-- Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Arria GX"
-- Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
-- Retrieval info: CONSTANT: ENABLE_SHARED_ACCESS STRING "ON"
-- Retrieval info: USED_PORT: asdo_in 0 0 0 0 INPUT NODEFVAL "ASDO_IN"
-- Retrieval info: USED_PORT: asmi_access_granted 0 0 0 0 INPUT NODEFVAL "ASMI_ACCESS_GRANTED"
-- Retrieval info: USED_PORT: asmi_access_request 0 0 0 0 OUTPUT NODEFVAL "ASMI_ACCESS_REQUEST"
-- Retrieval info: USED_PORT: data0_out 0 0 0 0 OUTPUT NODEFVAL "DATA0_OUT"
-- Retrieval info: USED_PORT: dclk_in 0 0 0 0 INPUT NODEFVAL "DCLK_IN"
-- Retrieval info: USED_PORT: ncso_in 0 0 0 0 INPUT NODEFVAL "nCSO_IN"
-- Retrieval info: USED_PORT: noe_in 0 0 0 0 INPUT NODEFVAL "nOE_IN"
-- Retrieval info: CONNECT: @sdoin 0 0 0 0 asdo_in 0 0 0 0
-- Retrieval info: CONNECT: asmi_access_request 0 0 0 0 @asmi_access_request 0 0 0 0
-- Retrieval info: CONNECT: @dclkin 0 0 0 0 dclk_in 0 0 0 0
-- Retrieval info: CONNECT: @scein 0 0 0 0 ncso_in 0 0 0 0
-- Retrieval info: CONNECT: @noe 0 0 0 0 noe_in 0 0 0 0
-- Retrieval info: CONNECT: @asmi_access_granted 0 0 0 0 asmi_access_granted 0 0 0 0
-- Retrieval info: CONNECT: data0_out 0 0 0 0 @data0out 0 0 0 0
-- Retrieval info: GEN_FILE: TYPE_NORMAL ASMI_Bridge.vhd TRUE FALSE
-- Retrieval info: GEN_FILE: TYPE_NORMAL ASMI_Bridge.inc FALSE FALSE
-- Retrieval info: GEN_FILE: TYPE_NORMAL ASMI_Bridge.cmp TRUE FALSE
-- Retrieval info: GEN_FILE: TYPE_NORMAL ASMI_Bridge.bsf TRUE FALSE
-- Retrieval info: GEN_FILE: TYPE_NORMAL ASMI_Bridge_inst.vhd TRUE FALSE
-- Retrieval info: LIB_FILE: altera_mf
