--------------------------------------------------------------------------------
-- revision information
--------------------------------------------------------------------------------
--	08.04.2008-le: - add to lib. esart
--  14.08.2008-qfu: - new macro from Esec
--                  - default value set for new signal "OutputEnable"
--------------------------------------------------------------------------------
--$Rev:: 489                                                                   $
--$Author:: Quirin                                                             $
--$Date:: 2008-08-14 14:18:25 +0200 (Do., 14 Aug 2008)                         $
--------------------------------------------------------------------------------


-- VHDL Entity E2_Slave.e2_ultralight.symbol
--
-- Created:
--          by - 17675.UNKNOWN (WD01ZG0742)
--          at - 16:10:58 13.08.2008
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2007.1 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY e2_ultralight IS
   GENERIC( 
      FirmID_User    : std_logic_vector( 15 DOWNTO 8 ) := x"00";
      PrintID        : std_logic_vector(15 downto 0)   := x"0000";
      SlaveAdr       : std_logic_vector(3 downto 0)    := x"0";
      RegisterInputs : boolean                         := FALSE
   );
   PORT( 
      INA          : IN     std_logic_vector (15 DOWNTO 0) := x"0000";
      INB          : IN     std_logic_vector (15 DOWNTO 0) := x"0000";
      INC          : IN     std_logic_vector (15 DOWNTO 0) := x"0000";
      OutputEnable : IN     std_logic := '1'; -- Debug QFU
      Rxd          : IN     std_logic;
      clk40        : IN     std_logic;
      reset_n      : IN     std_logic;
      ErrorLED     : OUT    std_logic;
      FreezeInputs : OUT    std_logic;
      OutA         : OUT    std_logic_vector (15 DOWNTO 0);
      OutB         : OUT    std_logic_vector (15 DOWNTO 0);
      OutC         : OUT    std_logic_vector (15 DOWNTO 0);
      Syn          : OUT    std_logic;
      Sync         : OUT    std_logic;
      Txd          : OUT    std_logic;
      UpdatePort   : OUT    std_logic_vector (2 DOWNTO 0)
   );

-- Declarations

END e2_ultralight ;

--
-- VHDL Architecture E2_Slave.e2_ultralight.struct
--
-- Created:
--          by - 17675.UNKNOWN (WD01ZG0742)
--          at - 16:10:58 13.08.2008
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2007.1 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


ARCHITECTURE struct OF e2_ultralight IS

   -- Architecture declarations
   TYPE port_type IS ARRAY (NATURAL RANGE <>) OF STD_LOGIC_VECTOR(15 DOWNTO 0);
   SUBTYPE port_matrix IS port_type (2 DOWNTO 0);

   -- Internal signal declarations
   SIGNAL AckBitsFlag     : boolean;
   SIGNAL AckIns          : std_logic;
   SIGNAL AdrOk           : std_logic;
   SIGNAL BitNr           : integer RANGE 0 TO 255;
   SIGNAL BitNr2          : integer RANGE 0 TO 2047;
   SIGNAL CaptureIn       : std_logic;
   SIGNAL ClearOut        : std_logic;
   SIGNAL Command         : std_logic_vector(4 DOWNTO 0);
   SIGNAL CommandActive   : std_logic;
   SIGNAL CommandFlag     : boolean;
   SIGNAL CommandFrame    : std_logic;
   SIGNAL CrcCmdFlag      : boolean;
   SIGNAL CrcDataFlag     : boolean;
   SIGNAL CrcEna          : std_logic;
   SIGNAL CrcRst          : std_logic;
   SIGNAL DataStreamOK    : std_logic;
   SIGNAL InPort          : port_matrix;
   SIGNAL InRegs          : port_matrix;
   SIGNAL MastermodeClock : std_logic_vector(4 DOWNTO 0);
   SIGNAL MbitNr          : integer RANGE 0 TO 127;
   SIGNAL OutPort         : port_matrix;
   SIGNAL ProtocolOk      : std_logic;
   SIGNAL ReceiveCKE      : std_logic;
   SIGNAL ReceiveSR       : std_logic_vector(24 DOWNTO 0);
   SIGNAL RxCmdValid      : std_logic;
   SIGNAL RxCmdValidFF    : std_logic;
   SIGNAL RxCrcOk         : std_logic;
   SIGNAL RxCrcShiftreg   : std_logic_vector(4 DOWNTO 0);
   SIGNAL RxDataValid     : std_logic;
   SIGNAL RxdQ            : std_logic_vector(2 DOWNTO 0);
   SIGNAL RxdSync         : std_logic_vector(4 DOWNTO 0);
   SIGNAL SlaveCRC        : std_logic_vector(4 DOWNTO 0);
   SIGNAL SlvAdrFlag      : boolean;
   SIGNAL Sr4Input        : std_logic;
   SIGNAL SyncEnable      : std_logic;
   SIGNAL SyncError       : std_logic;
   SIGNAL SyncFlag        : std_logic;
   SIGNAL SyncPatternFlag : boolean;
   SIGNAL TxCrcOut        : std_logic;
   SIGNAL TxCrcOutEna     : std_logic;
   SIGNAL TxCrcShiftreg   : std_logic_vector(4 DOWNTO 0);
   SIGNAL TxMuxOut        : std_logic_vector(15 DOWNTO 0);
   SIGNAL TxShiftreg      : std_logic_vector(16 DOWNTO 0);
   SIGNAL TxSrLoad        : std_logic;
   SIGNAL TxSrOut         : std_logic;
   SIGNAL TxTransparent   : std_logic;
   SIGNAL UpdateOut       : std_logic_vector(2 DOWNTO 0);
   SIGNAL ZerosOk         : std_logic;
   SIGNAL mastermode      : std_logic;
   SIGNAL mtx             : std_logic;


subtype CmdType is std_logic_vector(4 downto 0);
type CmdArrayType is array (0 to 2) of CmdType;
-- all output commands: InOutA, InOutB, InOutC
constant OutCmds: CmdArrayType:= ("01010","01011","00101");
constant InCmds:  CmdArrayType:= ("01000","01001","00100");
constant FirmID_Internal: std_logic_vector(7 downto 0):= x"04";


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 RxCrc
   -------------------------------------------------------------------
   --
   --  Beim vorliegenden CRC-Code handelt es sich um einen BCH-Code
   --  mit folgenden Daten:
   --               N (Blocklänge)         = 31 Bit
   --               K (Informationsbit)   = 26 Bit
   --               D (Hammingdistanz)   =  3
   --               N-K (Paritätsbit)      =  5 Bit
   --
   -- Obwohl im vorliegenden Fall nur 16 Bit codiert werden müssen, ist es doch
   -- möglich mit obenstehendem Code zu arbeiten. Da die Anzahl der zu kodierenden 
   -- Bits natürlich stimmen muss, wir jedoch nur 16 Nutzbits + 5 Bit CRC haben, muss dem
   -- rückgekoppelten CRC-Schieberegister eine bestimmte Anfangsbedingung vorgegaukelt werden.
   -- Diese Anfangsbedingung entspricht dem Wert, den man nach dem durchtakten von 5 Nullen
   -- an den Schieberegisterausgängen erhalten hätte. Die CRC-Ueberprüfung startet also
   -- eigentlich bei jedem Check bereits nach 5 Bits.
   --
   -- Siehe auch Buch "Fehlerkorrigierende BLOCK-Codierung für die
   -- Datenübertragung" (F.J.Furrer; Verlag Birkhäuser).
   --
   -- Rueckgekoppeltes Schieberegister fuer die 
   -- Ueberpruefung des CRCs.
   -- Mit rx_crc_rst wird das SR auf die Anfangsbedingung gesetzt.
   -- Mit NOT rx_crc_ena bleibt der alte Zustand erhalten (Nullen im Protokoll dürfen natürlich 
   -- nicht im CRC überprüft werden).
   -- Sind alle Bits "durchgeschoben" incl. Pruefsumme sollte RX_CRC_OK 1 sein sonst CRC-Fehler
   
   rx_crc_p: PROCESS(clk40)
   BEGIN
     IF rising_edge(clk40) then
        IF ReceiveCKE='1' then
        IF CrcRst = '1' THEN
           RxCrcShiftreg <= "00110";            -- setzen der Anfangsbedingung
        ELSIF CrcEna = '1' THEN                  -- Prüfsumme wird getestet (crc_ena nur aktiv bei eff. Nutzdaten)
           RxCrcShiftreg(4) <= ReceiveSR(24) XOR RxCrcShiftreg(0);
            RxCrcShiftreg(3) <= RxCrcShiftreg(4);
            RxCrcShiftreg(2) <= RxCrcShiftreg(3) XOR (ReceiveSR(24) XOR RxCrcShiftreg(0));
            RxCrcShiftreg(1) <= RxCrcShiftreg(2);
            RxCrcShiftreg(0) <= RxCrcShiftreg(1);
        END IF;
       END IF;
     END IF;
   END PROCESS rx_crc_p;
   
   RxCrcOk <= '1' WHEN RxCrcShiftreg = "00000" ELSE '0';   -- Der CRC ist okay wenn das Schieberegister am Schluss
                                                                  -- der Prüfung "00000" enthält!!!

   -- HDL Embedded Text Block 2 RxControl
   -- receive synchronization
   process(clk40) 
   variable i: integer;
   begin
      if rising_edge(clk40) then -- all synchronous
         if reset_n = '0' then --synchronous reset
           RxdQ <= "000";
           SyncEnable <= '1';
           RxdSync <= "00001"; --receive clock generator
           ReceiveSR <= (others => '0'); --receive shift register
           BitNr <= 0; --bit counter
           BitNr2 <= 0; --bit counter
           CommandActive <= '0';
           SyncError <= '0';
           MasterMode <= '0'; 
         else
   -- receive clock generation         
            RxdQ <= RxdQ(1 downto 0) & not Rxd; --synchronize incoming data
            if RxdQ(2 downto 1) = "01" and SyncEnable = '1' then --rising edge detected
               RxdSync <= "00001"; --synchronize receiver clock on rising edges
            else
               RxdSync <= RxdSync(3 downto 0) & RxdSync(4); --receiver clock
            end if;
          if (BitNr = 49) AND SyncError='0' and ReceiveCKE='1' then --sync pulse aligned with UpdatePort
             Sync <= '1';
          else 
             Sync <= '0';
          end if;
   
   -- 8 MHz receive synchronous from here...
            if ReceiveCKE='1' then -- running at 8 MHz
               ReceiveSR <= RxdQ(2) & ReceiveSR(ReceiveSR'left downto 1); --clock in receive data
               if SyncFlag = '1' then
                  SyncEnable <= '0'; --disable resynchronization during transmission
                  BitNr <= 0; --reset bit counter when sync packet is detected
                  BitNr2 <= 0; --reset bit counter when sync packet is detected
                  CommandActive <= '0';-- no command is active now
                  SyncError <= '0'; -- sync is OK.
                  MasterMode <= '0'; -- and no Mastermode.
               else
                  BitNr <= BitNr +1; --increment bit counter
                  BitNr2 <= BitNr2 +1; --increment bit counter
               -- Timeout and Mastermode Control
                  if BitNr2 = 1649 then -- 16 packets missed!
                     Mastermode <= '1';
                  end if;
                  if BitNr2 = 96 then -- 1 packet missed!
                     SyncError <= '1';
                  end if;
                  if BitNr = 81 then      -- enlarge sync window due to synchronisation problems on SSI++ (RXD pulses too short)
                     SyncEnable <= '1'; --enable resynchronization after packet is received
                  end if;
               end if;
               if BitNr=22 then -- check if slave address and protocol ID are OK and store command
                  if (ReceiveSR(13 downto 11) & ReceiveSR(9))=SlaveAdr then
                     AdrOK <= '1'; --Slave Adress is OK
                  else
                     AdrOK <= '0';
                  end if;
                  if ReceiveSR(5 downto 2)="0000" then
                     ProtocolOK <= '1'; --Protocol ID is OK
                  else
                     ProtocolOK <= '0';
                  end if;
                  Command<=ReceiveSR(18 downto 14); --store command
               end if;
               IF RxCmdValid = '1' AND ProtocolOk='1' and ((AdrOk='1') OR (Command = "00000") OR (Command = "11111")) THEN
                  CommandActive <= '1'; --Command is valid and will be executed
               end if;
            IF (BitNr = 23) THEN
               RxCmdValidFF <= RxCmdValid;
            END IF;
            for i in 0 to 2 loop --Output command decoding:
               if CommandActive = '1' and RxDataValid='1' and Command=OutCmds(i) then
                  UpdateOut(i)<='1';
               else
                  UpdateOut(i)<='0';
               end if;
            end loop;
          -- SYN: for compatibility only!
            IF (BitNr = 79) AND (SyncError = '0') THEN
               Syn <= '0';
            ELSIF (BitNr = 91) OR (SyncError = '1') THEN
               Syn <= '1';
            END IF;
            end if;
   -- end 8 MHz synchronous part
         end if;
      end if;
   end process;
   ReceiveCKE <= RxdSync(2); -- this is the receive clock enable
   --Sync control
   SyncFlag <= '1' WHEN ReceiveSR(ReceiveSR'left downto ReceiveSR'left-10) = "01111111110" ELSE '0';
   ZerosOk  <= NOT ReceiveSR(24) AND NOT ReceiveSR(18) AND NOT ReceiveSR(9) AND NOT ReceiveSR(0);
   --CRC control
   CrcRst <= '1' when SyncFlag='1' or BitNr=24 else '0'; -- reset CRC after Sync
   CrcEna <= '0' WHEN ((BitNr =  8) OR (BitNr = 33) OR (BitNr = 17) OR (BitNr = 42)) ELSE '1';
   -- Output control
   --UpdateO <= '1' WHEN ((BitNr = 48) AND (AdrProtocolOk='1') AND (SyncError = '0') AND (RxCrcOk = '1')) ELSE '0';
   RxCmdValid  <= '1' when (BitNr = 23) AND SyncError='0' AND RxCrcOk='1' AND ZerosOk='1' else '0';
   RxDataValid <= '1' when (BitNr = 48) AND SyncError='0' AND RxCrcOk='1' AND ZerosOk='1' else '0';
   
   -- Acknowledge control
   DataStreamOK  <= RxCmdValidFF AND RxDataValid;
   AckIns <= '1' WHEN ((BitNr = 48) AND (DataStreamOK = '1') AND ((AdrOk='1') OR (Command="00000") OR (Command="11111"))) ELSE '0';
   -- Transmit CRC control
   TxCrcOutEna <= '1' WHEN ((ProtocolOk = '1') AND ((AdrOk='1') OR (Command="00000") OR (command="11111")) AND (BitNr >= 43) AND (BitNr <= 52) AND (SyncError = '0')) ELSE '0';
   
   -- Transmit shift register control
   CommandFrame <= '1' WHEN ((BitNr >= 53) OR (BitNr <= 24)) ELSE '0';
   TxSrLoad <= '1' WHEN ((RxCmdValidFF = '1') AND (BitNr = 24)) ELSE '0';
   FreezeInputs <= '1' WHEN ((RxCmdValidFF = '1') AND (BitNr = 22)) and ReceiveCKE='1' ELSE '0';
   TxTransparent <= '1' WHEN ((SyncError='1') OR (ProtocolOk='0') OR (CommandFrame='1') OR (Command="00000") OR (Command="11110") OR (Command="11111") OR 
                                     (RxCmdValidFF='0') OR ((CommandFrame='0') AND (RxCmdValidFF='1') AND (AdrOK='0'))) ELSE '0';
   CaptureIn    <= '1' WHEN (BitNr = 85) ELSE '0'; -- latch input values - compatibility only
   -- clear output ports:
   ClearOut <= '1' when (CommandActive = '1' and (Command="11111" or Command="00000")) or Mastermode = '1' else '0';
   
   -- Error LED is active when Mastermode is received or sent
   ErrorLED <= '1' when Mastermode='1' or Command="11111" else '0';
   

   -- HDL Embedded Text Block 3 OutRegs
   OUTA <= OutPort(0);
   OUTB <= OutPort(1);
   OUTC <= OutPort(2);
   
   out_reg_p: PROCESS(clk40)
   variable i: integer;
   BEGIN
      IF rising_edge(clk40) then
         IF ClearOut = '1' or OutputEnable = '0' or reset_n = '0' THEN
            OutPort       <= (OTHERS => "0000000000000000");     -- alle Ausgangsports werden zurückgesetzt
            UpdatePort(2 DOWNTO 0) <= "000";
         ELSE                             -- Updates der Ausgangsports je nach aktuellem Command
            for i in 0 to 2 loop
               IF UpdateOut(i) = '1' THEN
                  OutPort(i) <= (ReceiveSR(16 DOWNTO 9) & ReceiveSR(7 DOWNTO 0));
                  UpdatePort(i) <=ReceiveCKE;
               else
                  UpdatePort(i) <='0';
               END IF;
            end loop;
         END IF;
      END IF;
   END PROCESS out_reg_p;
   
   
   

   -- HDL Embedded Text Block 4 mastermodegen
   process(clk40) begin
      if rising_edge(clk40) then
         if reset_n='0' then
            MastermodeClock <= "00001"; --generate stable clock enable for Masterclock
         else
            MastermodeClock <= MastermodeClock(3 downto 0) & MastermodeClock(4);
         end if;
         -- bit counter for generating the mastermode protocol
         if reset_n='0' or (MastermodeClock(4)='1' and (MbitNr=93 or Mastermode='0')) then
            MbitNr <= 0;
         elsif MastermodeClock(4)='1' then
            MbitNr <= MbitNr+1;
         end if;
      end if;
   end process;
   
   -- get Slave CRC from lookup table - remeber SlaveAdr is a generic!
   SlaveCRC <= "01001" WHEN SlaveAdr="0000" ELSE
            "10101" WHEN SlaveAdr="0001" ELSE
            "00111" WHEN SlaveAdr="0010" ELSE
            "11011" WHEN SlaveAdr="0011" ELSE
            "01110" WHEN SlaveAdr="0100" ELSE
            "10010" WHEN SlaveAdr="0101" ELSE
            "00000" WHEN SlaveAdr="0110" ELSE
            "11100" WHEN SlaveAdr="0111" ELSE
            "11000" WHEN SlaveAdr="1000" ELSE
            "00100" WHEN SlaveAdr="1001" ELSE
            "10110" WHEN SlaveAdr="1010" ELSE
            "01010" WHEN SlaveAdr="1011" ELSE
            "11111" WHEN SlaveAdr="1100" ELSE
            "00011" WHEN SlaveAdr="1101" ELSE
            "10001" WHEN SlaveAdr="1110" ELSE
            "01101" WHEN SlaveAdr="1111" ;
   
   -- Generate Mastermode protocol
   mcode_gen_p: PROCESS(clk40)
   BEGIN
     IF rising_edge(clk40) then
        IF SyncPatternFlag OR SlvAdrFlag OR CommandFlag OR AckBitsFlag OR CrcCmdFlag OR CrcDataFlag THEN
           mtx <= '1';    -- Mastermode-Protokolls wird hier auf den seriellen Ausgang geschaltet
        ELSE
           mtx <= '0';    -- Mastermode-Protokolls wird hier auf den seriellen Ausgang geschaltet
        END IF;
     END IF;
   END PROCESS mcode_gen_p;
   
   -- Hier werden die Positionen der entsprechenden Bits im Datenstrom festgelegt. Ist zum Beispiel
   -- die MbitNr<=23 und gleichzeitig auch <=27 wird das SIGNAL command = true. Im PROCESS mcode_gen_p
   -- werden darauf alle diese Statussignale abgefragt und falls true wird an dieser Stelle eine '1' IN den
   -- Datenstrom eingefügt (sonst '0').
   SyncPatternFlag   <= true WHEN ((MbitNr >= 1) AND (MbitNr <= 9)) ELSE false;      -- Synch-Pattern "01111111110"
   
   -- Slave-Adresse gemäss Einstellung
   SlvAdrFlag      <= true WHEN ((SlaveAdr(0)='1' AND (MbitNr = 18)) OR (SlaveAdr(1)='1' AND (MbitNr = 20)) OR 
                             (SlaveAdr(2)='1' AND (MbitNr = 21)) OR (SlaveAdr(3)='1' AND (MbitNr = 22))) ELSE false;
   
   -- Der CRC für den Commandblock ändert sich je nach eingestelltem Slave. D.h. es gibt 16 verschiedene Möglichkeiten.
   -- Diese 16 Codes wurden vorausberechnet und IN einer Tabelle abgelegt (LUT).
   CrcCmdFlag         <= true WHEN  ((SlaveCrc(4)='1' AND (MbitNr = 29)) OR (SlaveCrc(3)='1' AND (MbitNr = 30)) OR 
                                       (SlaveCrc(2)='1' AND (MbitNr = 31)) OR (SlaveCrc(1)='1' AND (MbitNr = 32)) OR 
                                  (SlaveCrc(0)='1' AND (MbitNr = 33))) ELSE false;
   CommandFlag       <= true WHEN ((MbitNr >= 23) AND (MbitNr <= 27)) ELSE false;    -- ergibt Command "11111" (Mastermode)
   AckBitsFlag          <= true WHEN ((MbitNr = 60) OR (MbitNr = 62)) ELSE false;       -- Ackbits "101" 
   
   -- Die Daten sind beim Mastermode-Protokoll immer 0. Darum wurde der CRC für diesen Wert vorausberechnet.
   -- Dies ergibt für den CRC der Daten folgenden Wert: "10100"
   CrcDataFlag          <= true WHEN ((MbitNr = 56) OR (MbitNr = 58)) ELSE false;

   -- HDL Embedded Text Block 5 inp
   InPort(0) <= INA;
   InPort(1) <= INB;
   InPort(2) <= INC;
   
   -- input register, for compatibility only! This is a massive waste of resources - use only if you must.
   process(clk40) begin
       if rising_edge(clk40) then
           if ReceiveCKE='1' then
               InRegs <= InPort;
           end if;
       end if;
   end process;
   
   
   -- select the value that will be sent depending on the command.
   process(InPort,Command)
   variable i:integer;
   variable o:std_logic_vector(15 downto 0);
   begin
       o := x"0000";
       for i in 0 to 2 loop
           if Command=InCmds(i) or Command=OutCmds(i) then --compare for inout and in commands
               if RegisterInputs then
                   o := InRegs(i);
               else
                   o := InPort(i);
               end if;
           end if;
       end loop;
       if Command="00011" then
           o := FirmID_User & FirmID_Internal;
       end if;
       if Command="00010" then
           o := PrintID;
       end if;
       TxMuxOut <= o;
   end process;
   

   -- HDL Embedded Text Block 6 TxControl
   process(clk40) begin
      if rising_edge(clk40) then
         -- transmit shift register
         IF reset_n = '0' THEN
            TxShiftreg <= (OTHERS => '0');
         elsif ReceiveCKE='1' then
             if TxSrLoad = '1' THEN --load register with transmit value
               TxShiftreg(7 DOWNTO 0)  <= TxMuxOut(7 DOWNTO 0);
               TxShiftreg(8)           <= '0';
               TxShiftreg(16 DOWNTO 9) <= TxMuxOut(15 DOWNTO 8);
            ELSE 
               TxShiftreg(16)          <= '0'; --shift register
               TxShiftreg(15 DOWNTO 0) <= TxShiftreg(16 DOWNTO 1);
            END IF;
         END IF;
         
         -- output FF and output multiplexer
         IF reset_n = '0' THEN
            TxCrcOut <= '0';
         elsif ReceiveCKE='1' then
            if TxCrcOutEna='1' then
               TxCrcOut <= TxCrcShiftreg(0);
            else
               TxCrcOut <= TxSrOut;
            end if;
         end if;
      end if;
   end process;
   
   -- switch between transmit and transparent mode
   TxSrOut <= ReceiveSR(24) WHEN TxTransparent = '1' ELSE TxShiftreg(0);
   -- mastermode output multiplexer
   txd <= mtx WHEN mastermode = '1' else TxCrcOut;

   -- HDL Embedded Text Block 7 TxCrc
   ----------------------------------------------
   
   -- Rueckgekoppeltes Schieberegister (SR) fuer die
   -- Erzeugung des CRCs.
   -- Das SR ist mit CRC_RST synchron ruecksetzbar.
   -- Mit !TX_CRC_ENA bleibt der alte Zustand erhalten.
   -- (Dies ist waehrend den eingeschobenen Nullen der Fall) 
   -- Mit TX_CRC_OUT_ENA wird der Inhalt des SR
   -- ohne weiteres Rueckkoppeln seriell herausgeschoben.
   -- (Ausgabe der Pruefsumme) Am Eingang des SR werden Nullen
   -- eingespeist.
   -- Ausgang ist TX_CRC_OUT.
   -- Das SR ist mit CLK8 getaktet
   
   -- Bei ACK_INS = 1 wird das SR mit "00101" geladen und seriell
   -- herausgeschoben. Dazu ist jedoch Bedingung, dass TX_CRC_OUT_ENA
   -- "1" ist. War das empfangene Protokoll ungültig, (ACK_INS = 0)
   -- wird das SR nicht geladen und es werden Nullen eingefügt.
   
   tx_crc_p: PROCESS(clk40)
   BEGIN
      IF rising_edge(clk40) then
            IF Reset_n='0' then
             TxCrcShiftreg <= "00110";    -- nur damit die Simulation netter aussieht, ansonsten unnötig
         ELSIF ReceiveCKE='1' then
            IF CrcRst = '1' THEN
               TxCrcShiftreg <= "00110";    -- Anfangsbedingung
            ELSIF (AckIns = '1') THEN
               TxCrcShiftreg <= "00101";
            ELSIF (CrcEna = '1') THEN
               TxCrcShiftreg(4) <= Sr4Input;
               TxCrcShiftreg(3) <= TxCrcShiftreg(4);
                TxCrcShiftreg(2) <= TxCrcShiftreg(3) XOR Sr4Input;
               TxCrcShiftreg(1) <= TxCrcShiftreg(2);
               TxCrcShiftreg(0) <= TxCrcShiftreg(1);
            END IF;
         END IF;
      END IF;
   END PROCESS tx_crc_p;
   
   Sr4Input <= ((TxSrOut XOR TxCrcShiftreg(0)) AND NOT TxCrcOutEna);


   -- Instance port mappings.

END struct;
