name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/niekdomi/vhdl-fmt/vhdlfmt-ci:latest
    env:
      CONAN_HOME: /root/.conan2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Cache Conan packages
        uses: actions/cache@v4
        with:
          path: /github/home/.conan2
          key: conan-${{ runner.os }}-${{ hashFiles('conanfile.txt') }}-v1
          restore-keys: |
            conan-${{ runner.os }}-v1
            conan-${{ runner.os }}-

      - name: Create and Publish Release
        uses: release-drafter/release-drafter@v6
        id: release-drafter
        with:
          config-name: release-drafter.yaml
          publish: true
          latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Release Binary
        run: |
          source venv/bin/activate
          make BUILD_TYPE=Release

      - name: Upload Binary to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.release-drafter.outputs.tag_name }}
          files: build/Release/bin/vhdl_formatter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
